# Generated by Django 3.1.4 on 2021-04-05 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cakmak',
            name='aciklama',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='cakmak',
            name='ana_foto',
            field=models.ImageField(blank=True, upload_to='fotolar/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='cakmak',
            name='fiyat',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cakmak',
            name='fonksiyon',
            field=models.CharField(choices=[('Taşlı', 'Taşlı'), ('Manyetolu', 'Manyetolu'), ('Rezistanslı', 'Rezistanslı')], default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cakmak',
            name='foto_1',
            field=models.ImageField(blank=True, upload_to='fotolar/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='cakmak',
            name='foto_2',
            field=models.ImageField(blank=True, upload_to='fotolar/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='cakmak',
            name='foto_3',
            field=models.ImageField(blank=True, upload_to='fotolar/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='cakmak',
            name='foto_4',
            field=models.ImageField(blank=True, upload_to='fotolar/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='cakmak',
            name='foto_5',
            field=models.ImageField(blank=True, upload_to='fotolar/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='cakmak',
            name='foto_6',
            field=models.ImageField(blank=True, upload_to='fotolar/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='cakmak',
            name='materyal',
            field=models.CharField(choices=[('Plastik', 'Plastik'), ('Metal', 'Metal')], default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cakmak',
            name='online',
            field=models.BooleanField(default=True),
        ),
    ]
