# Generated by Django 3.1.4 on 2021-04-05 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210405_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cakmak',
            name='fiyat',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
