# Generated by Django 3.1.4 on 2021-04-06 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210405_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='cakmak',
            name='adet',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
