# Generated by Django 3.1.4 on 2021-04-06 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_cakmak_adet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cakmak',
            old_name='adet',
            new_name='miktar',
        ),
    ]
