# Generated by Django 3.1.4 on 2021-04-09 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210406_1837'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cakmak',
            old_name='miktar',
            new_name='adet',
        ),
    ]
