# Generated by Django 3.1.4 on 2021-04-09 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20210409_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='cakmak',
            name='insert',
            field=models.BooleanField(default=False),
        ),
    ]
