# Generated by Django 3.1.4 on 2021-04-10 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_cakmak_insert'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, upload_to='logolar')),
            ],
        ),
    ]
