# Generated by Django 3.1.4 on 2021-04-10 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_marka'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marka',
            name='logo',
        ),
    ]
