# Generated by Django 3.1.4 on 2021-04-10 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_marka_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cakmak',
            old_name='foto_1',
            new_name='foto_7',
        ),
    ]
