# Generated by Django 2.2.7 on 2021-04-11 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_remove_cakmak_foto_7'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cakmak',
            options={'ordering': ['-no'], 'verbose_name': 'Çakmak', 'verbose_name_plural': 'Çakmaklar'},
        ),
        migrations.AlterModelOptions(
            name='marka',
            options={'verbose_name': 'Marka', 'verbose_name_plural': 'Markalar'},
        ),
    ]
